# Multi Regression Assignment #

In [96]:
# import libraries:
import pandas as pd

In [97]:
#Reading dataset:
dataset=pd.read_csv('Startups.csv')
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [98]:
# one column is categorical so we are going to convert this as number.it a nominal data so we go for one-hot encoding.
dataset=pd.get_dummies(dataset,drop_first=True)

In [99]:
dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False

In [100]:
#split input and output:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [101]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]
independent.head()

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10          False            True
1  162597.70       151377.59        443898.53          False           False
2  153441.51       101145.55        407934.54           True           False
3  144372.41       118671.85        383199.62          False            True
4  142107.34        91391.77        366168.42           True           False

In [102]:
dependent=dataset[['Profit']]
dependent.head()

      Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [103]:
#split train and test data:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [104]:
# model selection
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor

LinearRegression()

In [105]:
# Training or learning:
regressor.fit(x_train,y_train)

LinearRegression()

In [106]:
# find weight:
weight = regressor.coef_
weight

array([[7.90840255e-01, 3.01968165e-02, 3.10148566e-02, 4.63028992e+02,
        3.04799573e+02]])

In [107]:
# find bias
bias = regressor.intercept_
bias

array([42403.87087053])

In [108]:
# evaluate the learning:
from sklearn.metrics import r2_score
y_train_pred = regressor.predict(x_train)
train_r2 = r2_score(y_train, y_train_pred)
train_r2

0.951557126270021

In [109]:
# model is ready for testing:
test_y_pred = regressor.predict(x_test)
test_y_pred

array([[104282.76472172],
       [132536.88499212],
       [133910.85007766],
       [ 72584.77489417],
       [179920.9276189 ],
       [114549.31079234],
       [ 66444.43261346],
       [ 98404.96840122],
       [114499.82808602],
       [169367.50639895],
       [ 96522.6253998 ],
       [ 88040.6718287 ],
       [110949.99405525],
       [ 90419.1897851 ],
       [128020.46250064]])

In [110]:
# Evaluate the perforace comared to learning:
y_train_pred = regressor.predict(x_train)
train_r2 = r2_score(y_train, y_train_pred)
train_r2

0.951557126270021

In [111]:
# r2 value is near to 1 so it is a good model.

In [112]:
# store the modelname in one file:
filename = 'final_model_multi_linear_regression.sav'

In [113]:
# dump the model in named file:
import pickle
pickle.dump(regressor,open(filename,'wb'))

In [114]:
#file opened now we have to load the model in that file.
loaded_model=pickle.load(open('final_model_multi_linear_regression.sav','rb'))
loaded_model

LinearRegression()

In [115]:
result=loaded_model.predict([[1234,345,4565,1,0]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [116]:
result

array([[43994.79745873]])

In [117]:
#  test model r _score:
test_r_score = r2_score(y_test,y_pred)
test_r_score

0.9358680970046241